### PR TITLE
Camera + motor

### PR DESCRIPTION
**Pull request by igmen-j**
- Please check the comments

### CODE REVIEW

**Review by hoang22k — APPROVED** [review]
Still not seeing some sources. Maybe in a different location. Will check with Justin. But this can be merged.

**Comment by igmen-j** [comment]
Added the sources in the Pixy cam code.

**Review by igmen-j — COMMENTED** [review]
All done.

**Review by igmen-j — COMMENTED** [review]
Reviewed. Waiting on Danny to approve.

**Review by hoang22k — APPROVED** [review]

**Pull request merged**
